### ISSUE TITLE
After install: Unable to save plugin settings

### ISSUE THREAD

**Issue by bencetuzson** [bors2908/slack-share#10]
Version: IntelliJ IDEA 2023.1.2 (Ultimate Edition) [build #IU-231.9011.34]

After installation, I get the following exception:

me.bors.slack.share.secret.SlackShareBundledFileException: Data file, bundled with plugin, required for authentication was not found.
	at me.bors.slack.share.secret.SecretImporter.readFileContentJar(SecretImporter.kt:64)
	at me.bors.slack.share.secret.SecretImporter.readFileContent(SecretImporter.kt:45)
	at me.bors.slack.share.secret.SecretImporter.checkAndImport(SecretImporter.kt:18)
	at me.bors.slack.share.secret.SecretImporter.checkAndImport$default(SecretImporter.kt:13)
	at me.bors.slack.share.service.InitializationServiceAutomatic.beforeInit(InitializationServiceAutomatic.kt:13)
	at me.bors.slack.share.service.InitializationService.<init>(InitializationService.kt:20)
	at me.bors.slack.share.service.InitializationServiceAutomatic.<init>(InitializationServiceAutomatic.kt:7)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:54)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at me.bors.slack.share.listener.PostStartListener.runActivity(PostStartListener.kt:15)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$2.invokeSuspend(StartupManagerImpl.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	
![image](https://github.com/bors2908/slack-share/assets/58665094/f37a45bb-b14c-4d72-a61c-2e898ddfc375)

**Comment by bors2908** [comment]
@bencetuzson I'll investigate the issue and will let you know when it's fixed.

**Comment by bors2908** [comment]
@bencetuzson Looks like one of the plugin files was corrupted in IntelliJ Marketplace. 
I've pushed the update 0.9.11 to the Marketplace. That resolves this and some other issues.

Thank you for letting me know!

**Comment by bencetuzson** [comment]
@bors2908 Thank you for your work! Really appreciate it!
